
create table role(
role_id INT not null primary key generated by default as identity,
name varchar(100) not null check(name in('admin','customer')));

create table users(
user_id INT  not null,
role_id INT not null, 
email varchar(100) unique not null,
password varchar(100) not null,
name varchar(100) not null,
created_at timestamp default now(),
constraint fk_users_role foreign key (role_id) references role(role_id)
);

alter table users add primary key (user_id);

create table orders (
order_id INT primary key not null,
user_id INT not null, 
status varchar(100) check(status in('pending','paid','cancelled')) not null,
created_at timestamp default now(),
total_price decimal(10,2) not null,
constraint fk_orders_users foreign key (user_id) references users(user_id)
);
drop table orders cascade;
alter table order_item add constraint fk_order_item_orders foreign key (order_id) references orders(order_id);

create table order_item (
order_id INT not null,
exemplar_id INT not null,
primary key(order_id,exemplar_id),
constraint fk_order_item_orders foreign key (order_id) references orders(order_id),
constraint fk_order_item_exemplars foreign key (exemplar_id) references exemplars(exemplar_id)
);
create table exemplars(
exemplar_id INT primary key  not null,
condition varchar(10) check (condition in ('new','used','copy')) not null,
is_available boolean default true,
price decimal(20,2) not null);

create table books(
book_id INT primary key not null,
title varchar (100) not null,
year INT not null );

create table authors (
author_id INT primary key not null,
first_name varchar(100) not null,
last_name varchar(100) not null,
bio text);

create table book_authors (
book_id INT  not null,
author_id INT  not null,
primary key (book_id,author_id),
constraint fk_book_authors_books foreign key (book_id) references books(book_id),
constraint fk_book_authors_authors foreign key (author_id) references authors(author_id));

select * from role;
select * from users;
select distinct * from orders;
select * from order_item;
select * from exemplars;
select distinct * from books;
select * from authors;
select * from book_authors;

INSERT INTO role (name) VALUES ('admin');
INSERT INTO role (name) VALUES ('customer');


INSERT INTO users (user_id, role_id, email, password, name) VALUES
(1, 1, 'admin@mail.com',  'hashed_pass_1', 'Admin User'),
(2, 2, 'john@mail.com',   'hashed_pass_2', 'John Smith'),
(3, 2, 'emma@mail.com',   'hashed_pass_3', 'Emma Johnson'),
(4, 2, 'carlos@mail.com', 'hashed_pass_4', 'Carlos Garcia'),
(5, 2, 'yuki@mail.com',   'hashed_pass_5', 'Yuki Tanaka');


INSERT INTO authors (author_id, first_name, last_name, bio) VALUES
(1, 'George',  'Orwell',      'English novelist, author of 1984'),
(2, 'Gabriel', 'Garcia',      'Colombian author, wrote One Hundred Years of Solitude'),
(3, 'Haruki',  'Murakami',    'Japanese author known for Norwegian Wood'),
(4, 'Agatha',  'Christie',    'English crime novelist, author of Hercule Poirot series'),
(5, 'Ernest',  'Hemingway',   'American novelist, author of The Old Man and the Sea');


INSERT INTO books (book_id, title, year) VALUES
(1, '1984',                              1949),
(2, 'One Hundred Years of Solitude',     1967),
(3, 'Norwegian Wood',                    1987),
(4, 'Murder on the Orient Express',      1934),
(5, 'The Old Man and the Sea',           1952);


INSERT INTO book_authors (book_id, author_id) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5);


INSERT INTO exemplars (exemplar_id, condition, is_available, price) VALUES
(1,  'new',  true,  15.99),
(2,  'used', true,  8.50),
(3,  'copy', true,  5.00),
(4,  'new',  true,  18.00),
(5,  'used', false, 7.25),
(6,  'new',  true,  12.99),
(7,  'copy', true,  4.50),
(8,  'used', true,  9.00),
(9,  'new',  true,  20.00),
(10, 'copy', true,  3.75);


INSERT INTO orders (order_id, user_id, status, total_price) VALUES
(1, 2, 'paid',      24.49),
(2, 3, 'pending',   18.00),
(3, 4, 'cancelled', 8.50),
(4, 5, 'paid',      33.99),
(5, 2, 'pending',   4.50);


INSERT INTO order_item (order_id, exemplar_id) VALUES
(1, 1),
(1, 3),
(2, 4),
(3, 2),
(4, 6),
(4, 9),
(5, 7);

update orders 
set status = 'paid', total_price = 1000
where order_id in(1,2,3,4,5,6,7,8);
select * from orders;

select *
from books
where year >= 1950 or year between 1800 and 1949;

select * 
from users 
where email like 'carlos@m%l.com';

select * 
from users 
where name is not null;

select * from orders 
where status not in ('cancelled') and total_price > 100;

select first_name,bio
from authors
where bio in(
select bio 
from authors
where bio like '%ovelist%'
);
select price 
from exemplars 
where price > (
select avg(price)
from exemplars);

select condition 
from exemplars 
where exemplar_id in (select exemplar_id
from order_item
where order_id in 
(select order_id from orders where status ='paid'));

select condition,SUM(price)
from exemplars
group by condition;

select name,email 
from(select name,email,1 sort_order 
from users 
union 
select first_name,last_name,2
from authors)
order by sort_order; 

SELECT u.name as name, u.email as email, a.first_name as first_name, a.last_name as last_name
FROM users u
JOIN authors a ON u.user_id = a.author_id;

select e.exemplar_id,e.is_available AS в_наличии,e.condition as состояние,o.status as статус,e.price as цена 
from orders o 
join order_item oi on o.order_id=oi.order_id 
join exemplars e on e.exemplar_id=oi.exemplar_id;

select a.first_name,a.last_name,b.year,b.title
from authors a 
full outer join books b on b.title=a.first_name;

select a.first_name,a.last_name,b.year,b.title
from authors a 
left join books b on b.title=a.first_name;

SELECT condition, price,
       ROUND(price, 1) AS rounded_price
FROM exemplars;

SELECT price,
       CEIL(price)  AS rounded_up,
       FLOOR(price) AS rounded_down
FROM exemplars;

SELECT exemplar_id,
       ABS(price - 10.00) AS diff_from_10
FROM exemplars;

SELECT
  CONCAT(first_name, ' ', last_name) AS full_name
FROM authors;

SELECT
  title,
  REPLACE(title, 'Wood', 'Forest') AS new_title
FROM books;

SELECT
  TRIM(condition) AS clean_condition
FROM exemplars;

SELECT
  condition,
  ROUND(AVG(price), 2) AS avg_price
FROM exemplars
GROUP BY condition
ORDER BY avg_price DESC;

SELECT
  condition,
  ROUND(AVG(price), 2) AS avg_price
FROM exemplars
GROUP BY condition
HAVING AVG(price) > 8;



