[project]
name = "my-project"
version = "0.1.0"
description = ""
authors = [
    {name = "Misha"}
]
requires-python = ">=3.11"
dependencies = [
    "pyspark (==3.3.1)",
    "pandas (>=3.0.2,<4.0.0)",
    "click (==8.0.1)",
    "numpy (>=2.4.4,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
