name: CI

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jdk

      - name: Install dependencies
        run: pip install -r pyspark_task/requirements.txt

      - name: Run pylint
        run: pylint pyspark_task/src/py_spark_task.py --rcfile=pyspark_task/.pylintrc

      - name: Run tests
        run: pytest pyspark_task/tests/ -v